// <auto-generated />
namespace Freestyle.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class saveModelChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(saveModelChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "202008042041328_saveModelChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
